objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Applicaion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Grouping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grouping</label>
        <referenceTo>Grouping__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grouping__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Groupings</relationshipLabel>
        <relationshipName>Groupings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grouping_ID__c</fullName>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grouping ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Grouping</label>
    <nameField>
        <label>Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Topics</relationshipLabel>
        <relationshipName>Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tree.cls
public class tree {

    public tree(ApexPages.StandardController controller) {

    }


     public String application{
    get
    {
   string acc = [Select name,application_id__c from Application__c where id=:Apexpages.currentpage().getparameters().get('id')].name;
        return acc;
    }
    set;
    }

   public pageReference Expand(){
   pagereference p;
     p = new pageReference('/'+'apex/tree');
   return p;
   }

 public pageReference Collapse(){
   pagereference p;
     p = new pageReference('/'+'apex/tree1');
   return p;
   }

   

List<grouping__c> grouping;

public class Groups {
Grouping__c g;
Application__c a;
List<Category__c> cats;
List<Application__c> apps;
public Groups(Grouping__c gin) { g = gin;
cats = [Select c.Name, c.Grouping__r.Grouping_ID__c, c.Grouping__r.Name,
c.Grouping__c, (Select Name,Description__c From Topics__r) From Category__c c
where c.Grouping__c = :gin.id];
system.debug(cats);
}
public List<Category__c> getCategories() { return cats; }
public string getname() { return g.name; }
public string getid() { return g.id; }


}
 
public List<Groups> getgrouping() {
if(grouping == null)
grouping = [select name, id from Grouping__c
where application__r.id =:Apexpages.currentpage().getparameters().get('id')];
List<Groups> ret = new List<Groups>{};
for ( Grouping__c g:grouping) {
ret.add( new Groups( g ) );
}
return ret;
}

}