objects/ISO_Countries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ISO_CODE__c</fullName>
        <label>ISO CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>ISO Countries</label>
</CustomObject>

classes/CustomSettingsListController.cls
public with sharing class CustomSettingsListController {
 
    public String selectedIso {get;set;}
 
    public List<selectOption> isoCodes {
        get {
            List<selectOption> options = new List<selectOption>();
 
            for (ISO_Countries__c iso : ISO_Countries__c.getAll().values())
                options.add(new SelectOption(iso.ISO_Code__c,iso.Name+' - '+iso.ISO_Code__c));
            return options;
 
        }
        set;
    }
 
}