objects/Position__c.object
<CustomObject>
    <description>This object stores information about open job at our company</description>
    <fields>
        <fullName>MIn_Pay__c</fullName>
        <label>MIn Pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/positioncreate.cls
global class positioncreate implements Database.Batchable<sObject>{
public String query;

global database.querylocator start(Database.BatchableContext BC){
    return null;
}
    
global void execute(Database.BatchableContext BC, List<sObject> scope){
Position__c newtd = new Position__c(NAME= 'Salesforce', max_pay__c = 2000, min_pay__c=1000);
 {
insert newtd;
}
       }
  global void finish(Database.BatchableContext BC){}  
}