objects/Position__c.object
<CustomObject>
    <description>This object stores information about open job at our company</description>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HumanResources</fullName>
                </value>
                <value>
                    <fullName>InformationTechnology</fullName>
                </value>
                <value>
                    <fullName>RetailOperations</fullName>
                </value>
                <value>
                    <fullName>Warehousing</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/HelloWorld2TestClass.cls
@isTest 
private class HelloWorld2TestClass {
    static testMethod void validateHelloWorld2() {
      Position__c p = new Position__c(Name='Testfa1',Max_Pay__c=5000,Functional_Area__c='Finance');
       System.debug('This is new PositonXXXXXXXXX: '+p.Functional_Area__c);

       // Insert book 
    
       insert p;
        System.debug('Adil: '+p);
    
       // Retrieve the new book 
    
       p = [SELECT Name,Functional_Area__c FROM Position__c WHERE Id =:p.Id];
       System.debug('FAxxxxxxx: '+p.Functional_Area__c);

       // Test that the trigger correctly updated the price 
    
      System.assertEquals('Finance', p.Functional_Area__c);
    }
}