objects/Position__c.object
<CustomObject>
    <description>This object stores information about open job at our company</description>
    <fields>
        <fullName>Java__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Java</label>
        <type>Checkbox</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PositionDetails.cls
public class PositionDetails {

    public Position__c merch { get; set; }
    
    public PositionDetails() {
        this.merch = getPosition();
    }

    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Position__c.FieldSets.adiltest__Dimensions.getFields();
    }

    private Position__c getPosition() {
        String query = 'SELECT ';
        for(Schema.FieldSetMember f : this.getFields()) {
            query += f.getFieldPath() + ', ';
        }
        query += 'Id, Name,Java__c FROM Position__c LIMIT 1';
        return Database.query(query);
    }
}